/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { GapAssessment } from "./GapAssessment";
import { GapAssessmentCountArgs } from "./GapAssessmentCountArgs";
import { GapAssessmentFindManyArgs } from "./GapAssessmentFindManyArgs";
import { GapAssessmentFindUniqueArgs } from "./GapAssessmentFindUniqueArgs";
import { CreateGapAssessmentArgs } from "./CreateGapAssessmentArgs";
import { UpdateGapAssessmentArgs } from "./UpdateGapAssessmentArgs";
import { DeleteGapAssessmentArgs } from "./DeleteGapAssessmentArgs";
import { Department } from "../../department/base/Department";
import { GapAssessmentService } from "../gapAssessment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => GapAssessment)
export class GapAssessmentResolverBase {
  constructor(
    protected readonly service: GapAssessmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GapAssessment",
    action: "read",
    possession: "any",
  })
  async _gapAssessmentsMeta(
    @graphql.Args() args: GapAssessmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [GapAssessment])
  @nestAccessControl.UseRoles({
    resource: "GapAssessment",
    action: "read",
    possession: "any",
  })
  async gapAssessments(
    @graphql.Args() args: GapAssessmentFindManyArgs
  ): Promise<GapAssessment[]> {
    return this.service.gapAssessments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => GapAssessment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GapAssessment",
    action: "read",
    possession: "own",
  })
  async gapAssessment(
    @graphql.Args() args: GapAssessmentFindUniqueArgs
  ): Promise<GapAssessment | null> {
    const result = await this.service.gapAssessment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => GapAssessment)
  @nestAccessControl.UseRoles({
    resource: "GapAssessment",
    action: "create",
    possession: "any",
  })
  async createGapAssessment(
    @graphql.Args() args: CreateGapAssessmentArgs
  ): Promise<GapAssessment> {
    return await this.service.createGapAssessment({
      ...args,
      data: {
        ...args.data,

        department: args.data.department
          ? {
              connect: args.data.department,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => GapAssessment)
  @nestAccessControl.UseRoles({
    resource: "GapAssessment",
    action: "update",
    possession: "any",
  })
  async updateGapAssessment(
    @graphql.Args() args: UpdateGapAssessmentArgs
  ): Promise<GapAssessment | null> {
    try {
      return await this.service.updateGapAssessment({
        ...args,
        data: {
          ...args.data,

          department: args.data.department
            ? {
                connect: args.data.department,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GapAssessment)
  @nestAccessControl.UseRoles({
    resource: "GapAssessment",
    action: "delete",
    possession: "any",
  })
  async deleteGapAssessment(
    @graphql.Args() args: DeleteGapAssessmentArgs
  ): Promise<GapAssessment | null> {
    try {
      return await this.service.deleteGapAssessment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Department, {
    nullable: true,
    name: "department",
  })
  @nestAccessControl.UseRoles({
    resource: "Department",
    action: "read",
    possession: "any",
  })
  async getDepartment(
    @graphql.Parent() parent: GapAssessment
  ): Promise<Department | null> {
    const result = await this.service.getDepartment(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
