/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { License } from "./License";
import { LicenseCountArgs } from "./LicenseCountArgs";
import { LicenseFindManyArgs } from "./LicenseFindManyArgs";
import { LicenseFindUniqueArgs } from "./LicenseFindUniqueArgs";
import { CreateLicenseArgs } from "./CreateLicenseArgs";
import { UpdateLicenseArgs } from "./UpdateLicenseArgs";
import { DeleteLicenseArgs } from "./DeleteLicenseArgs";
import { User } from "../../user/base/User";
import { LicenseService } from "../license.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => License)
export class LicenseResolverBase {
  constructor(
    protected readonly service: LicenseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "License",
    action: "read",
    possession: "any",
  })
  async _licensesMeta(
    @graphql.Args() args: LicenseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [License])
  @nestAccessControl.UseRoles({
    resource: "License",
    action: "read",
    possession: "any",
  })
  async licenses(
    @graphql.Args() args: LicenseFindManyArgs
  ): Promise<License[]> {
    return this.service.licenses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => License, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "License",
    action: "read",
    possession: "own",
  })
  async license(
    @graphql.Args() args: LicenseFindUniqueArgs
  ): Promise<License | null> {
    const result = await this.service.license(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => License)
  @nestAccessControl.UseRoles({
    resource: "License",
    action: "create",
    possession: "any",
  })
  async createLicense(
    @graphql.Args() args: CreateLicenseArgs
  ): Promise<License> {
    return await this.service.createLicense({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => License)
  @nestAccessControl.UseRoles({
    resource: "License",
    action: "update",
    possession: "any",
  })
  async updateLicense(
    @graphql.Args() args: UpdateLicenseArgs
  ): Promise<License | null> {
    try {
      return await this.service.updateLicense({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => License)
  @nestAccessControl.UseRoles({
    resource: "License",
    action: "delete",
    possession: "any",
  })
  async deleteLicense(
    @graphql.Args() args: DeleteLicenseArgs
  ): Promise<License | null> {
    try {
      return await this.service.deleteLicense(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: License): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
