/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BiaCreateNestedManyWithoutDepartmentsInput } from "./BiaCreateNestedManyWithoutDepartmentsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { GapAssessmentCreateNestedManyWithoutDepartmentsInput } from "./GapAssessmentCreateNestedManyWithoutDepartmentsInput";
import { RiskAssessmentCreateNestedManyWithoutDepartmentsInput } from "./RiskAssessmentCreateNestedManyWithoutDepartmentsInput";

@InputType()
class DepartmentCreateInput {
  @ApiProperty({
    required: false,
    type: () => BiaCreateNestedManyWithoutDepartmentsInput,
  })
  @ValidateNested()
  @Type(() => BiaCreateNestedManyWithoutDepartmentsInput)
  @IsOptional()
  @Field(() => BiaCreateNestedManyWithoutDepartmentsInput, {
    nullable: true,
  })
  bias?: BiaCreateNestedManyWithoutDepartmentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  departmentDescription?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  departmentName?: string | null;

  @ApiProperty({
    required: false,
    type: () => GapAssessmentCreateNestedManyWithoutDepartmentsInput,
  })
  @ValidateNested()
  @Type(() => GapAssessmentCreateNestedManyWithoutDepartmentsInput)
  @IsOptional()
  @Field(() => GapAssessmentCreateNestedManyWithoutDepartmentsInput, {
    nullable: true,
  })
  gapAssessments?: GapAssessmentCreateNestedManyWithoutDepartmentsInput;

  @ApiProperty({
    required: false,
    type: () => RiskAssessmentCreateNestedManyWithoutDepartmentsInput,
  })
  @ValidateNested()
  @Type(() => RiskAssessmentCreateNestedManyWithoutDepartmentsInput)
  @IsOptional()
  @Field(() => RiskAssessmentCreateNestedManyWithoutDepartmentsInput, {
    nullable: true,
  })
  riskAssessments?: RiskAssessmentCreateNestedManyWithoutDepartmentsInput;
}

export { DepartmentCreateInput as DepartmentCreateInput };
