/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BiaListRelationFilter } from "../../bia/base/BiaListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { GapAssessmentListRelationFilter } from "../../gapAssessment/base/GapAssessmentListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { RiskAssessmentListRelationFilter } from "../../riskAssessment/base/RiskAssessmentListRelationFilter";

@InputType()
class DepartmentWhereInput {
  @ApiProperty({
    required: false,
    type: () => BiaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BiaListRelationFilter)
  @IsOptional()
  @Field(() => BiaListRelationFilter, {
    nullable: true,
  })
  bias?: BiaListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  departmentDescription?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  departmentName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => GapAssessmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GapAssessmentListRelationFilter)
  @IsOptional()
  @Field(() => GapAssessmentListRelationFilter, {
    nullable: true,
  })
  gapAssessments?: GapAssessmentListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => RiskAssessmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RiskAssessmentListRelationFilter)
  @IsOptional()
  @Field(() => RiskAssessmentListRelationFilter, {
    nullable: true,
  })
  riskAssessments?: RiskAssessmentListRelationFilter;
}

export { DepartmentWhereInput as DepartmentWhereInput };
