/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { RiskAssessment } from "./RiskAssessment";
import { RiskAssessmentCountArgs } from "./RiskAssessmentCountArgs";
import { RiskAssessmentFindManyArgs } from "./RiskAssessmentFindManyArgs";
import { RiskAssessmentFindUniqueArgs } from "./RiskAssessmentFindUniqueArgs";
import { CreateRiskAssessmentArgs } from "./CreateRiskAssessmentArgs";
import { UpdateRiskAssessmentArgs } from "./UpdateRiskAssessmentArgs";
import { DeleteRiskAssessmentArgs } from "./DeleteRiskAssessmentArgs";
import { Department } from "../../department/base/Department";
import { RiskAssessmentService } from "../riskAssessment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => RiskAssessment)
export class RiskAssessmentResolverBase {
  constructor(
    protected readonly service: RiskAssessmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "RiskAssessment",
    action: "read",
    possession: "any",
  })
  async _riskAssessmentsMeta(
    @graphql.Args() args: RiskAssessmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [RiskAssessment])
  @nestAccessControl.UseRoles({
    resource: "RiskAssessment",
    action: "read",
    possession: "any",
  })
  async riskAssessments(
    @graphql.Args() args: RiskAssessmentFindManyArgs
  ): Promise<RiskAssessment[]> {
    return this.service.riskAssessments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => RiskAssessment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "RiskAssessment",
    action: "read",
    possession: "own",
  })
  async riskAssessment(
    @graphql.Args() args: RiskAssessmentFindUniqueArgs
  ): Promise<RiskAssessment | null> {
    const result = await this.service.riskAssessment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => RiskAssessment)
  @nestAccessControl.UseRoles({
    resource: "RiskAssessment",
    action: "create",
    possession: "any",
  })
  async createRiskAssessment(
    @graphql.Args() args: CreateRiskAssessmentArgs
  ): Promise<RiskAssessment> {
    return await this.service.createRiskAssessment({
      ...args,
      data: {
        ...args.data,

        department: args.data.department
          ? {
              connect: args.data.department,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => RiskAssessment)
  @nestAccessControl.UseRoles({
    resource: "RiskAssessment",
    action: "update",
    possession: "any",
  })
  async updateRiskAssessment(
    @graphql.Args() args: UpdateRiskAssessmentArgs
  ): Promise<RiskAssessment | null> {
    try {
      return await this.service.updateRiskAssessment({
        ...args,
        data: {
          ...args.data,

          department: args.data.department
            ? {
                connect: args.data.department,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => RiskAssessment)
  @nestAccessControl.UseRoles({
    resource: "RiskAssessment",
    action: "delete",
    possession: "any",
  })
  async deleteRiskAssessment(
    @graphql.Args() args: DeleteRiskAssessmentArgs
  ): Promise<RiskAssessment | null> {
    try {
      return await this.service.deleteRiskAssessment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Department, {
    nullable: true,
    name: "department",
  })
  @nestAccessControl.UseRoles({
    resource: "Department",
    action: "read",
    possession: "any",
  })
  async getDepartment(
    @graphql.Parent() parent: RiskAssessment
  ): Promise<Department | null> {
    const result = await this.service.getDepartment(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
