/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { LicenseCreateNestedManyWithoutUsersInput } from "./LicenseCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { RoleManagementCreateNestedManyWithoutUsersInput } from "./RoleManagementCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LicenseCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LicenseCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LicenseCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  licenses?: LicenseCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => RoleManagementCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RoleManagementCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RoleManagementCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  roleManagements?: RoleManagementCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
